# Generated by Django 2.2.1 on 2019-05-16 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='J', max_length=1, verbose_name='Tipo')),
                ('xp_total', models.FloatField(blank=True, default=0)),
                ('m_realizadas', models.IntegerField(blank=True, default=0)),
                ('m_adquiridas', models.IntegerField(blank=True, default=0)),
                ('mr_nadata', models.IntegerField(blank=True, default=0)),
                ('private_token', models.CharField(max_length=100)),
                ('url_imagem', models.CharField(default='', max_length=300)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jogador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
