# Generated by Django 2.2.1 on 2019-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_jogadoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadoritem',
            name='quantidade_bloqueada',
            field=models.IntegerField(default=0),
        ),
    ]
