# Generated by Django 2.2.1 on 2019-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0003_jogadoritem_quantidade_bloqueada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='desafios_v',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
