# Generated by Django 2.2.1 on 2019-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0005_auto_20190519_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='eventos_v',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
