# Generated by Django 2.2.1 on 2019-05-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_auto_20190518_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='desafiado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Desafiado', to='jogador.Jogador'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='item_desafiado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemDesafiado', to='jogador.JogadorItem'),
        ),
    ]
