# Generated by Django 2.2.1 on 2019-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_auto_20190518_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='status',
            field=models.CharField(choices=[('P', 'Proposta'), ('A', 'Aposta'), ('E', 'Em Andamento'), ('C', 'Conslusão')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
