# Generated by Django 2.2.1 on 2019-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0005_auto_20190519_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='vencedor',
            field=models.CharField(choices=[('DE', 'Desafiante'), ('DO', 'Desafiado')], max_length=2, null=True, verbose_name='Status'),
        ),
    ]
