# Generated by Django 2.2.1 on 2019-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_desafio_vencedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafiomissoes',
            name='xp_ganha',
            field=models.IntegerField(null=True),
        ),
    ]
