# Generated by Django 2.2.1 on 2019-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0008_auto_20190519_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafiomissoes',
            name='xp_ganha',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
