# Generated by Django 2.2.1 on 2019-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0009_auto_20190519_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='vencedor',
            field=models.CharField(blank=True, choices=[('DE', 'Desafiante'), ('DO', 'Desafiado'), ('EM', 'Empate')], max_length=2, null=True, verbose_name='Vencedor'),
        ),
    ]
