# Generated by Django 2.2.1 on 2019-05-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0010_auto_20190519_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='item_desafiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemDesafiante', to='jogador.JogadorItem'),
        ),
    ]
