# Generated by Django 2.2.1 on 2019-05-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_missao', models.CharField(max_length=200)),
                ('xp_missao', models.FloatField()),
                ('data', models.CharField(blank=True, default='', max_length=100)),
                ('nice_tempo', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('id_issue', models.IntegerField(default=0)),
                ('id_projeto', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jogador', to='jogador.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='MissãoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('xp_missao', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MissãoGrupo', to='missao.Missao')),
            ],
        ),
    ]
