# Generated by Django 2.2.1 on 2019-05-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='xp_ganha',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
