# Generated by Django 2.2.1 on 2019-05-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0003_missao_nice_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('xp_grupo', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('id_milestone', models.IntegerField(default=0)),
                ('participantes', models.CharField(default='jogador', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='MissãoGrupo',
        ),
    ]
