# Generated by Django 2.2.1 on 2019-05-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burndown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('quantidade_missao', models.IntegerField(blank=True, default=0)),
                ('quantidade_queimada', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MissaoBurndown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burndown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Burndown', to='burndown.Burndown')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MissaoBurndown', to='missao.Missao')),
            ],
        ),
    ]
