# Generated by Django 2.2.1 on 2019-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burndown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burndown',
            name='quantidade_queimada',
        ),
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
