# Generated by Django 2.2.1 on 2019-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burndown', '0002_auto_20190526_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='burndown',
            name='quantidade_queimada_dia0',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='burndown',
            name='quantidade_queimada_dia1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='burndown',
            name='quantidade_queimada_dia2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='burndown',
            name='quantidade_queimada_dia3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='burndown',
            name='quantidade_queimada_dia4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='burndown',
            name='quantidade_queimada_dia5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
