# Generated by Django 2.2.1 on 2019-05-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burndown', '0004_auto_20190526_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissaoBurndown',
        ),
    ]
