# Generated by Django 2.2.1 on 2019-05-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='primeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item1', to='evento.Item'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item4', to='evento.Item'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quinto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item5', to='evento.Item'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='segundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item2', to='evento.Item'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sexto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item6', to='evento.Item'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item3', to='evento.Item'),
        ),
    ]
