# Generated by Django 2.2.1 on 2019-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20190519_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='is_finalized',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
